{% set name = "Lektor" %}
{% set version = "3.1" %}
{% set hash_type = "sha256" %}
{% set hash = "2ec5f8b6b813d4fbf9d45fc05a3cd374f87dc5590f8690fbd9855d3007b0b38f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - lektor = lektor.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - babel
    - click >=6.0
    - exifread
    - flask
    - inifile
    - jinja2 >=2.4
    - mistune >=0.7.0
    - ndg-httpsclient
    - nodejs
    - pyasn1
    - pyopenssl >=0.13
    - python
    - requests
    - watchdog

test:
  imports:
    - lektor

  commands:
    - lektor --help

about:
  home: https://getlektor.com
  license: BSD 3-Clause
  license_family: BSD
  summary: The lektor static file content management system.
  description: |
    A flexible and powerful static content management system for building
    complex and beautiful websites out of flat files for people who do not
    want to make a compromise between a CMS and a static blog engine.
  dev_url: https://github.com/lektor/lektor
  doc_url: https://www.getlektor.com/docs

extra:
  recipe-maintainers:
    - goanpeca
    - rlaverde
